import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseClaudeLines, isHumanPrompt, CLAUDE_PARSER_VERSION } from '../../../src/providers/claude/parse.ts';
import type { TailLine } from '../../../src/providers/claude/tail.ts';

function linesOf(fixture: string): TailLine[] {
  const raw = readFileSync(join('tests/fixtures/claude', fixture), 'utf8');
  const out: TailLine[] = [];
  let offset = 0;
  for (const text of raw.split('\n')) {
    if (text.trim()) out.push({ text, offset });
    offset += Buffer.byteLength(text, 'utf8') + 1;
  }
  return out;
}

describe('isHumanPrompt', () => {
  it('accepts a plain string content', () => {
    expect(isHumanPrompt({ message: { content: 'hello' } })).toBe(true);
  });

  it('REJECTS a tool_result — the revision-1 bug', () => {
    expect(isHumanPrompt({ message: { content: [{ type: 'tool_result', tool_use_id: 't' }] } }))
      .toBe(false);
  });

  it('accepts a text block array', () => {
    expect(isHumanPrompt({ message: { content: [{ type: 'text', text: 'hi' }] } })).toBe(true);
  });

  it('accepts an image plus text array', () => {
    expect(isHumanPrompt({ message: { content: [
      { type: 'image', source: {} }, { type: 'text', text: 'look' },
    ] } })).toBe(true);
  });

  it('rejects a mixed array containing any tool_result', () => {
    expect(isHumanPrompt({ message: { content: [
      { type: 'text', text: 'hi' }, { type: 'tool_result', tool_use_id: 't' },
    ] } })).toBe(false);
  });
});

// Measured on session 92b09bc5: 246 "you" rows, 40 actually typed. Records
// that carry `origin` are labelled by Claude Code itself, so the label wins.
describe('isHumanPrompt -- origin label', () => {
  it('accepts a record labelled origin.kind human', () => {
    expect(isHumanPrompt({ origin: { kind: 'human' }, message: { content: 'ship it' } })).toBe(true);
  });

  it('rejects a record labelled task-notification, even though its content is a plain string', () => {
    expect(isHumanPrompt({
      origin: { kind: 'task-notification' },
      message: { content: '<task-notification>\n<task-id>b1</task-id>\n</task-notification>' },
    })).toBe(false);
  });

  it('rejects a record labelled peer (another Claude session)', () => {
    expect(isHumanPrompt({ origin: { kind: 'peer' }, message: { content: 'hello from a peer' } })).toBe(false);
  });

  it('rejects an isMeta record even when it claims origin human', () => {
    expect(isHumanPrompt({ isMeta: true, origin: { kind: 'human' }, message: { content: 'x' } })).toBe(false);
  });
});

// Unlabelled records: every record from CLI versions before the label, plus
// labelled-era records Claude Code writes without one (sdk-py sessions, a
// first prompt that begins with a path, slash commands, bash mode).
describe('isHumanPrompt -- unlabelled fallback', () => {
  const plain = (content: unknown, extra: Record<string, unknown> = {}) => ({ ...extra, message: { content } });

  it('rejects isMeta records (skill bodies, context usage, image stubs)', () => {
    expect(isHumanPrompt(plain('Base directory for this skill: /x', { isMeta: true }))).toBe(false);
  });

  it('rejects a compact summary', () => {
    expect(isHumanPrompt(plain('This session is being continued from a previous conversation', {
      isCompactSummary: true, isVisibleInTranscriptOnly: true,
    }))).toBe(false);
  });

  it.each([
    'Another Claude session sent a message: <teammate-message teammate_id="lead">hi</teammate-message>',
    '<teammate-message teammate_id="lead">hi</teammate-message>',
    '<task-notification>\n<task-id>b1</task-id>\n</task-notification>',
    'Base directory for this skill: /Users/x/.claude/skills/foo',
    '## Context Usage\n\n**Model:** claude-opus-5',
    '<bash-input>ps -Ao pid</bash-input>',
    '<bash-stdout>12 node</bash-stdout><bash-stderr></bash-stderr>',
    '<bash-stderr>boom</bash-stderr>',
    '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
    '<local-command-stdout>Goodbye!</local-command-stdout>',
    '<local-command-stderr>nope</local-command-stderr>',
    '[Request interrupted by user]',
    '[Request interrupted by user for tool use]',
  ])('rejects the known wrapper %j', (text) => {
    expect(isHumanPrompt(plain(text))).toBe(false);
    expect(isHumanPrompt(plain([{ type: 'text', text }]))).toBe(false);
  });

  it('keeps an unlabelled plain prompt (older CLI, sdk-py, path-first prompt)', () => {
    expect(isHumanPrompt(plain('/Users/me/repo We have the game adventure 101'))).toBe(true);
  });

  it('keeps a slash-command invocation so the conversation view can unwrap it', () => {
    expect(isHumanPrompt(plain('<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>'))).toBe(true);
  });
});

describe('parseClaudeLines', () => {
  const events = parseClaudeLines(linesOf('basic.jsonl'), '/f.jsonl');

  it('emits exactly two prompt.submitted events, not five', () => {
    const prompts = events.filter(e => e.kind === 'prompt.submitted');
    expect(prompts).toHaveLength(2);
    expect(prompts.map(p => p.payload.text)).toEqual([
      'Wire up magic-link auth.', 'Set it to 15 minutes.',
    ]);
  });

  it('emits session.started once, from the first record carrying cwd', () => {
    const started = events.filter(e => e.kind === 'session.started');
    expect(started).toHaveLength(1);
    expect(started[0]!.payload).toMatchObject({ provider: 'claude', cwd: '/repo' });
  });

  it('emits prose for assistant text blocks', () => {
    const prose = events.filter(e => e.kind === 'prose');
    expect(prose.map(p => p.payload.text)).toEqual([
      'Reusing the existing JWT helper.', 'The magic link has no expiry.',
    ]);
  });

  it('emits tool.used with name and target', () => {
    const tools = events.filter(e => e.kind === 'tool.used');
    expect(tools).toHaveLength(1);
    expect(tools[0]!.payload).toMatchObject({ name: 'Read', target: '/repo/src/auth.js' });
  });

  it('emits turn.completed with token counts', () => {
    const turns = events.filter(e => e.kind === 'turn.completed');
    expect(turns).toHaveLength(2);
    expect(turns[0]!.payload).toMatchObject({ inputTokens: 10, outputTokens: 5 });
  });

  it('carries the source offset and content hash on every event', () => {
    for (const e of events) {
      expect(e.sourceFile).toBe('/f.jsonl');
      expect(e.contentHash).toMatch(/^[0-9a-f]{64}$/);
      expect(typeof e.sourceOffset).toBe('number');
    }
  });

  it('stores an unknown record type as unparsed rather than dropping it', () => {
    const evs = parseClaudeLines(linesOf('unknown-record.jsonl'), '/f.jsonl');
    const unparsed = evs.filter(e => e.kind === 'unparsed');
    expect(unparsed).toHaveLength(1);
    expect(unparsed[0]!.payload).toMatchObject({ recordType: 'telemetry-v9' });
  });

  it('silences a known-but-unmapped record type -- no event at all, not even unparsed', () => {
    const evs = parseClaudeLines(
      [{ text: JSON.stringify({ type: 'attachment', sessionId: 's1', timestamp: '2026-09-10T00:00:00.000Z' }), offset: 0 }],
      '/f.jsonl',
    );
    expect(evs).toHaveLength(0);
  });

  // Measured: 7 human messages in session 92b09bc5 were typed while the agent
  // was busy and stored only as a queued_command attachment. Across the
  // whole corpus none of these 230 were also written as a user record (0
  // source_uuid matches), so emitting them cannot double-count.
  describe('queued_command attachments', () => {
    const queued = (attachment: Record<string, unknown>, extra: Record<string, unknown> = {}) => ({
      text: JSON.stringify({
        type: 'attachment', sessionId: 's1', uuid: 'att-1', timestamp: '2026-09-12T05:21:34.675Z',
        attachment: { type: 'queued_command', ...attachment }, ...extra,
      }),
      offset: 0,
    });

    it('emits prompt.submitted for a human message typed while the agent was busy', () => {
      const evs = parseClaudeLines([queued({
        prompt: 'Are you sure?', commandMode: 'prompt', origin: { kind: 'human' },
      })], '/f.jsonl');
      expect(evs).toHaveLength(1);
      expect(evs[0]).toMatchObject({
        kind: 'prompt.submitted', payload: { text: 'Are you sure?' },
        sessionId: 's1', ts: '2026-09-12T05:21:34.675Z', nativeId: 'att-1', agentId: null,
      });
    });

    it('takes the text blocks when the queued prompt is a content array (a pasted image)', () => {
      const evs = parseClaudeLines([queued({
        prompt: [{ type: 'text', text: '[Image #3] make it orange' }, { type: 'image', source: {} }],
        commandMode: 'prompt', origin: { kind: 'human' },
      })], '/f.jsonl');
      expect(evs.map(e => e.payload.text)).toEqual(['[Image #3] make it orange']);
    });

    it('emits nothing for a queued task notification, labelled or not', () => {
      const text = '<task-notification>\n<task-id>b1</task-id>\n</task-notification>';
      expect(parseClaudeLines([queued({ prompt: text, commandMode: 'task-notification' })], '/f.jsonl')).toHaveLength(0);
      expect(parseClaudeLines([queued({
        prompt: text, commandMode: 'task-notification', origin: { kind: 'task-notification' },
      })], '/f.jsonl')).toHaveLength(0);
    });

    it('emits nothing for a queued message from a peer session', () => {
      expect(parseClaudeLines([queued({
        prompt: 'hi', commandMode: 'prompt', origin: { kind: 'peer' },
      })], '/f.jsonl')).toHaveLength(0);
    });

    it('still silences every other attachment type', () => {
      expect(parseClaudeLines([queued({ type: 'hook_success', origin: { kind: 'human' } })], '/f.jsonl')).toHaveLength(0);
    });
  });

  it('emits no prompt.submitted for a teammate message or a task notification user record', () => {
    const rec = (content: string, extra: Record<string, unknown> = {}) => ({
      text: JSON.stringify({ type: 'user', sessionId: 's1', timestamp: '2026-09-12T00:00:00Z', uuid: 'u', message: { role: 'user', content }, ...extra }),
      offset: 0,
    });
    const evs = parseClaudeLines([
      rec('Another Claude session sent a message: <teammate-message teammate_id="a">done</teammate-message>'),
      { ...rec('<task-notification>x</task-notification>', { origin: { kind: 'task-notification' } }), offset: 10 },
      { ...rec('real question', { origin: { kind: 'human' } }), offset: 20 },
    ], '/f.jsonl');
    expect(evs.filter(e => e.kind === 'prompt.submitted').map(e => e.payload.text)).toEqual(['real question']);
  });

  it('bumps the parser version so already-indexed transcripts are reparsed', () => {
    expect(CLAUDE_PARSER_VERSION).toBe(3);
  });

  it('still reports a genuinely unrecognized type as unparsed -- recognising the known-unmapped set does not blunt the drift signal', () => {
    const evs = parseClaudeLines(linesOf('unknown-record.jsonl'), '/f.jsonl');
    const unparsed = evs.filter(e => e.kind === 'unparsed');
    expect(unparsed).toHaveLength(1);
    expect(unparsed[0]!.payload).toMatchObject({ recordType: 'telemetry-v9' });
  });

  it('stores a corrupt line as unparsed rather than throwing', () => {
    const evs = parseClaudeLines([{ text: 'not json at all', offset: 0 }], '/f.jsonl');
    expect(evs).toHaveLength(1);
    expect(evs[0]!.kind).toBe('unparsed');
  });

  it('emits 8 events from basic.jsonl, each with a distinct (sourceOffset, subIndex) pair', () => {
    expect(events).toHaveLength(8);
    const pairs = events.map(e => `${e.sourceOffset}:${e.subIndex}`);
    expect(new Set(pairs).size).toBe(pairs.length);
  });

  it('restarts subIndex at 0 for each new source line', () => {
    const byOffset = new Map<number, number[]>();
    for (const e of events) {
      const list = byOffset.get(e.sourceOffset) ?? [];
      list.push(e.subIndex);
      byOffset.set(e.sourceOffset, list);
    }
    for (const subIndices of byOffset.values()) {
      expect(subIndices[0]).toBe(0);
      expect(subIndices).toEqual(subIndices.map((_, i) => i));
    }
  });
});

// B3: real Claude records ALL carry cwd (basic.jsonl's later lines omit it
// only because it is trimmed for fixture brevity), and sessionStartEmitted
// used to reset to false on every invocation of parseClaudeLines -- so a
// tail chunk resumed mid-file, whose first record still carried cwd,
// re-emitted a second session.started for the same session.
describe('parseClaudeLines — resume context (B3)', () => {
  const tailRecord = (uuid: string) => JSON.stringify({
    type: 'assistant', sessionId: 's1', cwd: '/repo', timestamp: '2026-09-10T00:00:05.000Z',
    message: { role: 'assistant', content: [{ type: 'text', text: 'still going' }] }, uuid,
  });

  it('emits no second session.started when resumed with sessionStartEmitted: true', () => {
    const evs = parseClaudeLines(
      [{ text: tailRecord('u6'), offset: 999 }], '/f.jsonl',
      { sessionId: 's1', sessionStartEmitted: true },
    );
    expect(evs.filter(e => e.kind === 'session.started')).toHaveLength(0);
  });

  it('carries the resumed session id even on a record with no sessionId field', () => {
    const noSessionId = JSON.stringify({
      type: 'assistant', cwd: '/repo', timestamp: '2026-09-10T00:00:05.000Z',
      message: { role: 'assistant', content: [{ type: 'text', text: 'still going' }] }, uuid: 'u7',
    });
    const evs = parseClaudeLines(
      [{ text: noSessionId, offset: 999 }], '/f.jsonl',
      { sessionId: 's1', sessionStartEmitted: true },
    );
    expect(evs.every(e => e.sessionId === 's1')).toBe(true);
  });

  it('still emits session.started on a from-zero parse (no resume context)', () => {
    const evs = parseClaudeLines([{ text: tailRecord('u6'), offset: 0 }], '/f.jsonl');
    expect(evs.filter(e => e.kind === 'session.started')).toHaveLength(1);
  });
});
